apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-quarkus-app
spec:
  params:
  - name: src
    value: .
  - name: image-name
    value: image-registry.openshift-image-registry.svc:5000/tekton/workshop-tekton-argocd-app-quarkus
  - name: service-name
    value: quarkus-app
  - name: container-file
    value: src/main/docker/Dockerfile.jvm
  - name: skip-image-push
    value: "false"