apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogs
  namespace: openshift-gitops
spec:
  destination:
    namespace: gogs
    server: "https://kubernetes.default.svc"
  source:
    path: dependencies/gogs
    repoURL: "https://github.com/dbgjerez/workshop-tekton-argocd"
    targetRevision: develop
  project: workshop-tekton-argocd
  syncPolicy:
    automated:
      prune: true
