apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-triggers
  namespace: openshift-gitops
spec:
  destination:
    namespace: tekton
    server: "https://kubernetes.default.svc"
  source:
    path: triggers
    repoURL: "https://github.com/dbgjerez/workshop-tekton-argocd"
    targetRevision: develop
  project: workshop-tekton-argocd
  syncPolicy:
    automated:
      prune: true
