apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workshop-tekton-argocd
  namespace: openshift-gitops
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/dbgjerez/workshop-tekton-argocd.git
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'